### ISSUE TITLE
Filter and sort commit types

### ISSUE THREAD

**Issue by snorremd** [go-fjords/turbo-monorepo-release-action#45]
Support sorting and filtering the conventional commit types.

Right now the order of the conventional commit types are in the order they first appear in the commit log. So if the first commit in the commit range is a `fix:` commit it will be the first type to appear in the release message. This is not necessarily the wanted behaviour. Often times `feature` is the most important type of commit as it tells the user what new features have been launched.

Order and filtering can be done via a list of conventional commit types as an input to the action. For example:

```yaml
 - name: Create release
    uses: go-fjords/create-release-from-deployment-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        workspace: my-workspace
        prefix: 'My App'
        from: 6b81ece3474de57f7fa070192fa1b88e303acb2a
        to: ${{ github.event.deployment.ref }}
        commit-types: |-
          feature
          fix
          build
          docs
```

This config would include only `feature`, `fix`, `build` and `docs` commits in that order. `ci` and any other commit type would be filtered out.

Considerations:

You might want the full release in GitHub and only filter when setting the output for use in Slack and other places. So perhaps two separate inputs, one for GitHub release and one for the action output.
